//! Primary entities in Jaymi's knowledge graph.
//!
//! Entities form the nodes of the graph. Relationships connect them.

use jaymi_core::EntityId;

/// Owner of the system.
#[derive(Debug, Clone)]
pub struct User {
    pub id: EntityId,
}

/// Conversation between the user and Jaymi.
#[derive(Debug, Clone)]
pub struct Conversation {
    pub id: EntityId,
}

/// Persistent workspace.
#[derive(Debug, Clone)]
pub struct Project {
    pub id: EntityId,
}

/// Intentionally retained knowledge.
#[derive(Debug, Clone)]
pub struct Memory {
    pub id: EntityId,
}

/// Indexed file reference (not a duplicated blob by default).
///
/// Layer 1 stores metadata in SQLite via [`crate::IndexedFile`]. This entity
/// remains the graph-facing identity for future relationships.
#[derive(Debug, Clone)]
pub struct File {
    pub id: EntityId,
    /// Absolute path when known.
    pub path: Option<std::path::PathBuf>,
    /// Index root label when known.
    pub source_root: Option<String>,
}

/// Content generated by Jaymi.
#[derive(Debug, Clone)]
pub struct Artifact {
    pub id: EntityId,
}

/// Optional unit of work in progress.
#[derive(Debug, Clone)]
pub struct Task {
    pub id: EntityId,
}

/// Installed provider record.
#[derive(Debug, Clone)]
pub struct Provider {
    pub id: EntityId,
}

/// Executable operation record.
#[derive(Debug, Clone)]
pub struct Tool {
    pub id: EntityId,
}
