[package]
name = "jaymi-tools"
description = "Tool framework and Tool Orchestrator for Jaymi"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
jaymi-capabilities = { workspace = true }
jaymi-core = { workspace = true }
jaymi-database = { workspace = true }
jaymi-parsers = { workspace = true }
jaymi-providers = { workspace = true }
